project:
  type: website

website:
  title: "My Quarto Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
